//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReolMarkedetNet.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_F23_TEAM_11Entities2 : DbContext
    {
        public DB_F23_TEAM_11Entities2()
            : base("name=DB_F23_TEAM_11Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Shelf> Shelf { get; set; }
        public virtual DbSet<ShelfOwner> ShelfOwner { get; set; }
        public virtual DbSet<ShelfProduct> ShelfProduct { get; set; }
    }
}
