//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReolMarkedetNet.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ShelfProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShelfProduct()
        {
            this.Sale = new HashSet<Sale>();
        }

        [Key]
        public int productId { get; set; }
        public string barcode { get; set; }
        public string productDescription { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> shelfId { get; set; }
        public Nullable<int> ownerId { get; set; }
    
        public virtual Shelf Shelf { get; set; }
        public virtual ShelfOwner ShelfOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }
    }
}
